PUT http://localhost:8200/events/1
Content-Type: application/json

{
    "name": "Updated test event",
    "description": "A test event",
    "location": "Test location updated",
    "dateTime":"2024-01-01T15:30:00Z"
}